Turn off unused-but-set-variable warning
We turn off the warning for all external projects. However
wpa_supplicant_8's sources are included directly by a platform project (hostapd_cf), causing it not to inherit the warning suppression.

Original failure:
FAILED:
out/soong/.intermediates/device/google/cuttlefish/guest/hals/hostapd/hostapd_cf/android_vendor_arm64_armv8-2a_cortex-a55/obj/external/wpa_supplicant_8/hostapd/config_file.o
external/wpa_supplicant_8/hostapd/config_file.c:4979:6: error: variable 'errors' set but not used [-Werror,-Wunused-but-set-variable]
 4979 |         int errors = 0;
      |

Change-Id: Ib137db00a219825339930d12f4b9b64a2793aab1